"""Render leaderboard outputs in JSON, Markdown, and HTML."""

from __future__ import annotations

import datetime as dt
import html
import json
from pathlib import Path

from raucle_bench.dataset import summarise
from raucle_bench.scoring import Score


def build_report(scores: list[Score], prompts: list, run_id: str | None = None) -> dict:
    """Build the canonical machine-readable report."""
    return {
        "run_id": run_id or dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "schema_version": "raucle-bench-report/v1",
        "dataset": summarise(prompts),
        "leaderboard": sorted(
            [s.to_dict() for s in scores],
            key=lambda d: (-d["f1"], -d["detection_rate"], d["false_positive_rate"]),
        ),
    }


def write_json(report: dict, path: str | Path) -> None:
    Path(path).write_text(json.dumps(report, indent=2, sort_keys=True))


def render_markdown(report: dict) -> str:
    """Render the leaderboard as a GitHub-flavoured Markdown table."""
    lines: list[str] = []
    lines.append(f"# Raucle-bench leaderboard — `{report['run_id']}`")
    lines.append("")
    ds = report["dataset"]
    by_class = ds.get("by_attack_class", {})
    by_class_str = ", ".join(f"{k}={v}" for k, v in sorted(by_class.items()))
    lines.append(f"**Dataset**: {ds['total']} prompts ({by_class_str})")
    lines.append("")
    header_row = (
        "| Adapter | F1 | Detection rate | False-positive rate "
        "| Strict match | p50 latency | p99 latency |"
    )
    lines.append(header_row)
    lines.append("|---|---:|---:|---:|---:|---:|---:|")
    for row in report["leaderboard"]:
        if row.get("setup_failed"):
            lines.append(
                f"| `{row['adapter_name']}` (v{row['adapter_version']}) "
                f"| — | — | — | — | — | _setup failed: {row['setup_failed']}_ |"
            )
            continue
        lines.append(
            f"| `{row['adapter_name']}` (v{row['adapter_version']}) "
            f"| {row['f1']:.3f} "
            f"| {row['detection_rate']:.1%} "
            f"| {row['false_positive_rate']:.1%} "
            f"| {row['strict_match_rate']:.1%} "
            f"| {row['latency_p50_ms']:.2f} ms "
            f"| {row['latency_p99_ms']:.2f} ms |"
        )
    lines.append("")
    lines.append(
        f"_Generated by raucle-bench on {report['run_id']}. Schema {report['schema_version']}._"
    )
    return "\n".join(lines) + "\n"


def render_html(report: dict) -> str:
    """Render a standalone HTML leaderboard suitable for bench.raucle.com."""
    rows: list[str] = []
    for row in report["leaderboard"]:
        if row.get("setup_failed"):
            rows.append(
                f"<tr><td><code>{html.escape(row['adapter_name'])}</code> "
                f"<span class='ver'>v{html.escape(row['adapter_version'])}</span></td>"
                f"<td colspan='6' class='err'>setup failed: "
                f"{html.escape(row['setup_failed'])}</td></tr>"
            )
            continue
        rows.append(
            "<tr>"
            f"<td><code>{html.escape(row['adapter_name'])}</code> "
            f"<span class='ver'>v{html.escape(row['adapter_version'])}</span></td>"
            f"<td class='num'>{row['f1']:.3f}</td>"
            f"<td class='num'>{row['detection_rate']:.1%}</td>"
            f"<td class='num'>{row['false_positive_rate']:.1%}</td>"
            f"<td class='num'>{row['strict_match_rate']:.1%}</td>"
            f"<td class='num'>{row['latency_p50_ms']:.2f} ms</td>"
            f"<td class='num'>{row['latency_p99_ms']:.2f} ms</td>"
            "</tr>"
        )

    ds = report["dataset"]
    by_class = ds.get("by_attack_class", {})
    dataset_desc = f"{ds['total']} prompts across " + ", ".join(
        f"{k}={v}" for k, v in sorted(by_class.items())
    )

    style = """
        :root { --bg:#fff; --text:#111218; --muted:#6b7280; --border:#e5e7eb; --soft:#f8f9fb; }
        body { font-family:'Inter',system-ui,sans-serif; color:var(--text); margin:0;
               background:var(--bg); line-height:1.6; }
        .container { max-width:960px; margin:0 auto; padding:48px 24px; }
        h1 { font-family:'Space Grotesk',sans-serif; font-size:2.2rem; margin:0 0 12px 0;
             letter-spacing:-0.02em; }
        p.lede { color:var(--muted); margin:0 0 36px 0; }
        table { width:100%; border-collapse:collapse; font-size:0.95rem; }
        th, td { padding:12px 14px; text-align:left; border-bottom:1px solid var(--border); }
        th { background:var(--soft); font-weight:600; font-family:'Space Grotesk',sans-serif; }
        td.num { font-variant-numeric:tabular-nums; text-align:right; }
        code { font-family:'JetBrains Mono',ui-monospace,monospace; font-size:0.88em; }
        .ver { color:var(--muted); font-size:0.85em; }
        .err { color:#b42318; font-style:italic; }
        footer { color:var(--muted); margin-top:48px; font-size:0.85rem; }
        footer a { color:var(--muted); }
    """

    return f"""<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Raucle-bench leaderboard</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Space+Grotesk:wght@500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>{style}</style>
</head><body>
<main class="container">
<h1>Raucle-bench leaderboard</h1>
<p class="lede">{html.escape(dataset_desc)}. Run <code>{html.escape(report["run_id"])}</code>.</p>
<table>
<thead><tr>
<th>Adapter</th><th>F1</th><th>Detection rate</th><th>FPR</th>
<th>Strict match</th><th>p50 latency</th><th>p99 latency</th>
</tr></thead>
<tbody>
{"".join(rows)}
</tbody>
</table>
<footer>Generated by <a href="https://github.com/craigamcw/raucle-bench">raucle-bench</a> ·
schema {html.escape(report["schema_version"])}.</footer>
</main>
</body></html>
"""
